import Struct from '~/classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 32, as: 'hex' } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: Number, name: 'nClass', len: 8 } },
  { child: { type: Number, name: 'bActivate', len: 8 } },
  { child: { type: Number, name: 'nMastIndex', len: 8 } },
  { child: { type: Number, name: 'nLv', len: 8 } },
  { child: { type: String, name: 'strMastEngName', len: 32 } },
  { child: { type: String, name: 'strMastKorName', len: 32 } },
  { child: { type: String, name: 'strEngName', len: 32 } },
  { child: { type: String, name: 'strKorName', len: 32 } },
  {
    child: [
      { type: Number, name: 'nContEffectTarget', len: 8 },
      { child: { type: Number, name: 'nContParamIndex', len: 8 }, repeat: 7 },
      { type: Number, name: 'nContParamCode', len: 32 },
      {
        child: { type: Number, name: 'fContValue', len: 32, as: 'float' },
        repeat: 7,
      },
    ],
    repeat: 7,
  },
  {
    child: { type: Number, name: 'nContEffectSec', len: 32 },
    repeat: 7,
  },
  { type: Boolean, name: 'bUsableRaceBM', len: 8 },
  { type: Boolean, name: 'bUsableRaceBF', len: 8 },
  { type: Boolean, name: 'bUsableRaceCM', len: 8 },
  { type: Boolean, name: 'bUsableRaceCF', len: 8 },
  { type: Boolean, name: 'bUsableRaceAM', len: 8 },
  { type: Boolean, name: 'bUsableRaceAF', len: 8 },
  { type: Number, name: 'nUnk16__1', len: 16 },
  { type: Number, name: 'nClassLim', len: 8 },
  { child: { type: Number, name: 'nActableDst', len: 8 }, repeat: 5 },
  { type: Number, name: 'nUnk8__1', len: 8 },
  { type: Number, name: 'nUnk16__2', len: 16 },
  { type: Number, name: 'nNeedMastIndex', len: 8 },
  { child: { type: Number, name: 'nFixWeapon', len: 8 }, repeat: 16 },
  { type: Number, name: 'nUnk16__3', len: 16 },
  { type: Number, name: 'nUnk32__1', len: 32 },
  { type: Number, name: 'nUnk32__2', len: 32 },
  { type: Number, name: 'nUnk32__3', len: 32 },
  { type: Number, name: 'fUnk32__1', len: 32, as: 'float' },
  { type: Boolean, name: 'bFixshield', len: 32 },
  { type: Number, name: 'nSpecialType', len: 8 },
  { type: Number, name: 'nNeedSpecialType', len: 8 },
  { type: Number, name: 'nNeedHP', len: 16 },
  { type: Number, name: 'nNeedFP', len: 16 },
  { type: Number, name: 'nNeedSP', len: 16 },
  { type: Number, name: 'fActDelay', len: 32, as: 'float' },
  { type: Number, name: 'fBonusDistance', len: 32, as: 'float' },
  { type: String, name: 'strDescription', len: 512 },
  { type: Number, name: 'nEffectClass', len: 32 },
  { child: { type: Number, name: 'nAttackType', len: 32 }, repeat: 2 },
  { child: { type: Number, name: 'nAttackValue', len: 32 }, repeat: 2 },
  { child: { type: Number, name: 'nSbeValue', len: 8 }, repeat: 12 },
  { type: String, name: 'strAura', len: 32, as: 'hex' },
  { type: String, name: 'strUnkX32__1', len: 32, as: 'hex' },
  { type: String, name: 'strUnkX32__2', len: 32, as: 'hex' },
  { type: String, name: 'strUnkX32__3', len: 32, as: 'hex' },
  { type: String, name: 'strUnkX32__4', len: 32, as: 'hex' },
  { type: Number, name: 'nUnk8__2', len: 8 },
  { type: Number, name: 'nUnk8__3', len: 8 },
  { type: Number, name: 'nUnk8__4', len: 8 },
  { type: Number, name: 'nUnk8__5', len: 8 },
  { type: Number, name: 'nAttNeedBt', len: 32 },
  { type: Number, name: 'nUnk32__4', len: 32 },
  { type: Number, name: 'f1s2spd', len: 32, as: 'float' },
  { type: Number, name: 'f2s3spd', len: 32, as: 'float' },
  { type: Number, name: 'nUnk32__5', len: 32 },
  { type: Number, name: 'f1s2dst', len: 32, as: 'float' },
  { type: Number, name: 'f2s3dst', len: 32, as: 'float' },
]);
