import * as ITEM_TYPES from 'structs/item_types';

import SegmentBasic from './Segment/Basic';
import SegmentBasicArmor from './Segment/BasicArmor';

// want help in writing specific components ;)
export default {
  [ITEM_TYPES.FACE]: SegmentBasic,
  [ITEM_TYPES.UPPER]: SegmentBasicArmor,
  [ITEM_TYPES.LOWER]: SegmentBasicArmor,
  [ITEM_TYPES.GAUNTLET]: SegmentBasicArmor,
  [ITEM_TYPES.SHOE]: SegmentBasicArmor,
  [ITEM_TYPES.HELMET]: SegmentBasicArmor,
  [ITEM_TYPES.WEAPON]: SegmentBasic,
  [ITEM_TYPES.SHIELD]: SegmentBasicArmor,
  [ITEM_TYPES.CLOAK]: SegmentBasic,
  [ITEM_TYPES.RING]: SegmentBasic,
  [ITEM_TYPES.AMULET]: SegmentBasic,
  [ITEM_TYPES.BULLET]: SegmentBasic,
  [ITEM_TYPES.MAKETOOL]: SegmentBasic,
  [ITEM_TYPES.POTION]: SegmentBasic,
  [ITEM_TYPES.BAG]: SegmentBasic,
  [ITEM_TYPES.BATTERY]: SegmentBasic,
  [ITEM_TYPES.ORE]: SegmentBasic,
  [ITEM_TYPES.RESOURCE]: SegmentBasic,
  [ITEM_TYPES.FORCE]: SegmentBasic,
  [ITEM_TYPES.UNITKEY]: SegmentBasic,
  [ITEM_TYPES.BOOTY]: SegmentBasic,
  [ITEM_TYPES.MAP]: SegmentBasic,
  [ITEM_TYPES.TOWN]: SegmentBasic,
  [ITEM_TYPES.DUNGEONKEY]: SegmentBasic,
  [ITEM_TYPES.ANIMUS]: SegmentBasic,
  [ITEM_TYPES.TOWER]: SegmentBasic,
  [ITEM_TYPES.TRAP]: SegmentBasic,
  [ITEM_TYPES.SIEGEKIT]: SegmentBasic,
  [ITEM_TYPES.TICKET]: SegmentBasic,
  [ITEM_TYPES.QUEST]: SegmentBasic,
  [ITEM_TYPES.RECOVERY]: SegmentBasic,
  [ITEM_TYPES.BOX]: SegmentBasic,
  [ITEM_TYPES.FIRECRACKER]: SegmentBasic,
  [ITEM_TYPES.CASHMINING]: SegmentBasic,
  [ITEM_TYPES.RADAR]: SegmentBasic,
  [ITEM_TYPES.PAGER]: SegmentBasic,
  [ITEM_TYPES.COUPON]: SegmentBasic,
  [ITEM_TYPES.MAUHEAD]: SegmentBasic,
  [ITEM_TYPES.MAUUPPER]: SegmentBasic,
  [ITEM_TYPES.MAULOWER]: SegmentBasic,
  [ITEM_TYPES.MAUARM]: SegmentBasic,
  [ITEM_TYPES.MAUSHOULDER]: SegmentBasic,
  [ITEM_TYPES.MAUBACK]: SegmentBasic,
  [ITEM_TYPES.MAUBULLET]: SegmentBasic,
  [ITEM_TYPES.MAKEDATA]: null,
  [ITEM_TYPES.COMBINEDATA]: null,
  [ITEM_TYPES.UNK3]: null,
};
