import Struct from '~/classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 64 } },
  { child: { type: Boolean, name: 'bExist', len: 32 } },
  { child: { type: String, name: 'strModel', len: 64 } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: String, name: 'strName', len: 64 } },
  { child: { type: Number, name: 'nKindClt', len: 32 } },
  { child: { type: Number, name: 'nFixPart', len: 32 } },
  { child: { type: Number, name: 'nItemSerise', len: 32 } },
  { child: { type: String, name: 'strCivil', len: 64 } },
  { child: { type: Number, name: 'nMixNum', len: 32 } },
  { child: { type: Number, name: 'fNeedNum', len: 32, as: 'float' } },
  { child: { type: String, name: 'strLastItem', len: 64 } },
  { child: { type: Number, name: 'nMoney', len: 32 } },
  { child: { type: Number, name: 'nAncStdPrice', len: 32 } },
  { child: { type: Number, name: 'nExStdPrice', len: 32 } },
  { child: { type: Number, name: 'nMecaStdPrice', len: 32 } },
  { child: { type: Number, name: 'nStdPoint', len: 32 } },
  { child: { type: Number, name: 'nGoldPoint', len: 32 } },
  { child: { type: Number, name: 'nKillPoint', len: 32 } },
  { child: { type: Number, name: 'nProcPoint', len: 32 } },
  { child: { type: Number, name: 'nStoragePrice', len: 32 } },
  { child: { type: Number, name: 'nStartTime', len: 32 } },
  { child: { type: Number, name: 'nEffContTime', len: 32 } },
  { child: { type: Number, name: 'nEffType1', len: 32 } },
  { child: { type: Number, name: 'nUIPrint', len: 32 } },
  { child: { type: Number, name: 'nItemUITip', len: 32 } },
  { child: { type: Number, name: 'nEffectDataNum', len: 32 } },
  { child: { type: Number, name: 'nEffCode__1', len: 32 } },
  { child: { type: Number, name: 'fEffUnit__1', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffUnitMax__1', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__2', len: 32 } },
  { child: { type: Number, name: 'fEffUnit__2', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffUnitMax__2', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__3', len: 32 } },
  { child: { type: Number, name: 'fEffUnit__3', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffUnitMax__3', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__4', len: 32 } },
  { child: { type: Number, name: 'fEffUnit__4', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffUnitMax__4', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__5', len: 32 } },
  { child: { type: Number, name: 'fEffUnit__5', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffUnitMax__5', len: 32, as: 'float' } },
  { child: { type: Boolean, name: 'bSell', len: 32 } },
  { child: { type: Boolean, name: 'bExchange', len: 32 } },
  { child: { type: Boolean, name: 'bGround', len: 32 } },
  { child: { type: Boolean, name: 'bStoragePossible', len: 32 } },
  { child: { type: Boolean, name: 'bUseableNormalAcc', len: 32 } },
  { child: { type: String, name: 'strTooltipIndex', len: 64 } },
  { child: { type: Boolean, name: 'bIsCash', len: 32 } },
  { child: { type: Number, name: 'nUsePCCash', len: 32 } },
  { child: { type: Boolean, name: 'bIsTime', len: 32 } },
]);
