import Struct from '../../../classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 64 } },
  { child: { type: Boolean, name: 'bExist', len: 32 } },
  { child: { type: Number, name: 'nType', len: 32 } },
  { child: { type: String, name: 'strModel', len: 64 } },
  { child: { type: String, name: 'strCharMeshID', len: 64 } },
  { child: { type: String, name: 'strName', len: 64 } },
  { child: { type: String, name: 'strCivil', len: 64 } },
  { child: { type: Number, name: 'nLevel', len: 32 } },
  { child: { type: Number, name: 'nLevelLim', len: 32 } },
  { child: { type: Number, name: 'nUpLevelLim', len: 32 } },
  { child: { type: Number, name: 'nExpertLim', len: 32 } },
  { child: { type: Number, name: 'nExpTimeSec', len: 32 } },
  { child: { type: Boolean, name: 'bDisjointable', len: 32 } },
  { child: { type: Number, name: 'nUpkeepTimeMin', len: 32 } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: Number, name: 'fReactionDst', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fAttGap', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nAttackDP', len: 32 } },
  { child: { type: Number, name: 'fGADst', len: 32, as: 'float' } },
  { child: { type: Boolean, name: 'bSetTarget', len: 32 } },
  { child: { type: Number, name: 'nAttSklUnit', len: 32 } },
  { child: { type: Number, name: 'nGAMinAF', len: 32 } },
  { child: { type: Number, name: 'nGAMaxAF', len: 32 } },
  { child: { type: Number, name: 'nGAMinSelProb', len: 32 } },
  { child: { type: Number, name: 'nGAMaxSelProb', len: 32 } },
  { child: { type: Number, name: 'fMaxHP', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nDefSklUnit', len: 32 } },
  { child: { type: Number, name: 'nDefFc', len: 32 } },
  { child: { type: Number, name: 'fDefGap', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fDefFacing', len: 32, as: 'float' } },
  { child: { type: String, name: 'strEffCode', len: 64 } },
  { child: { type: Number, name: 'nProperty', len: 32 } },
  { child: { type: Number, name: 'nFireTol', len: 32 } },
  { child: { type: Number, name: 'nWaterTol', len: 32 } },
  { child: { type: Number, name: 'nSoilTol', len: 32 } },
  { child: { type: Number, name: 'nWindTol', len: 32 } },
  { child: { type: Number, name: 'nEffCode__1', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__1', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__2', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__2', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nDuration', len: 32 } },
  { child: { type: Number, name: 'nMoney', len: 32 } },
  { child: { type: Number, name: 'nStdPrice', len: 32 } },
  { child: { type: Number, name: 'nStdPoint', len: 32 } },
  { child: { type: Number, name: 'nGoldPoint', len: 32 } },
  { child: { type: Number, name: 'nKillPoint', len: 32 } },
  { child: { type: Number, name: 'nProcPoint', len: 32 } },
  { child: { type: Number, name: 'nStoragePrice', len: 32 } },
  { child: { type: Boolean, name: 'bDismantle', len: 32 } },
  { child: { type: Boolean, name: 'bSell', len: 32 } },
  { child: { type: Boolean, name: 'bExchange', len: 32 } },
  { child: { type: Boolean, name: 'bGround', len: 32 } },
  { child: { type: Boolean, name: 'bStoragePossible', len: 32 } },
  { child: { type: Boolean, name: 'bUseableNormalAcc', len: 32 } },
  { child: { type: Boolean, name: 'bUpgrade', len: 32 } },
  { child: { type: String, name: 'strTooltipIndex', len: 64 } },
  { child: { type: Number, name: 'nAttEffType', len: 32 } },
  { child: { type: Number, name: 'nDefEffType', len: 32 } },
  { child: { type: Boolean, name: 'bIsTime', len: 32 } },
]);
