import Struct from '../../../classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 64 } },
  { child: { type: Boolean, name: 'bExist', len: 32 } },
  { child: { type: String, name: 'strModel', len: 64 } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: String, name: 'strName', len: 64 } },
  { child: { type: Number, name: 'nKindClt', len: 32 } },
  { child: { type: Number, name: 'nItemGrade', len: 32 } },
  { child: { type: Number, name: 'nActiveType', len: 32 } },
  { child: { type: String, name: 'strActiveCodeKey', len: 64 } },
  { child: { type: Number, name: 'nActiveEffLvl', len: 32 } },
  { child: { type: Number, name: 'fActiveProba', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nFixPart', len: 32 } },
  { child: { type: String, name: 'strBulletType', len: 64 } },
  { child: { type: String, name: 'strEffBulletType', len: 64 } },
  { child: { type: Number, name: 'nWPType', len: 32 } },
  { child: { type: Number, name: 'nSubType', len: 32 } },
  { child: { type: String, name: 'strCivil', len: 64 } },
  { child: { type: String, name: 'strClassLim', len: 64 } },
  { child: { type: Number, name: 'nLevelLim', len: 32 } },
  { child: { type: Number, name: 'nUpLevelLim', len: 32 } },
  { child: { type: Number, name: 'nClassGradeLim', len: 32 } },
  { child: { type: Number, name: 'nExpertID1', len: 32 } },
  { child: { type: Number, name: 'nExpertLim1', len: 32 } },
  { child: { type: Number, name: 'nExpertID2', len: 32 } },
  { child: { type: Number, name: 'nExpertLim2', len: 32 } },
  { child: { type: Number, name: 'nMoney', len: 32 } },
  { child: { type: Number, name: 'nStdPrice', len: 32 } },
  { child: { type: Number, name: 'nStdPoint', len: 32 } },
  { child: { type: Number, name: 'nGoldPoint', len: 32 } },
  { child: { type: Number, name: 'nKillPoint', len: 32 } },
  { child: { type: Number, name: 'nProcPoint', len: 32 } },
  { child: { type: Number, name: 'nStoragePrice', len: 32 } },
  { child: { type: Boolean, name: 'bAbr', len: 32 } },
  { child: { type: Number, name: 'nDurUnit', len: 32 } },
  { child: { type: Number, name: 'fEquipSpeed', len: 32, as: 'float' } },
  { child: { type: Boolean, name: 'bRepair', len: 32 } },
  { child: { type: Number, name: 'nRepPrice', len: 32 } },
  { child: { type: Number, name: 'nEffState', len: 32 } },
  { child: { type: Number, name: 'nProperty', len: 32 } },
  { child: { type: Number, name: 'fFireTol', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fWaterTol', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fSoilTol', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fWindTol', len: 32, as: 'float' } },
  { child: { type: Number, name: 'fAttGap', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nAttackDP', len: 32 } },
  { child: { type: Number, name: 'fGADst', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nGASpd', len: 32 } },
  { child: { type: Number, name: 'nGAMinSelProb', len: 32 } },
  { child: { type: Number, name: 'fGAMinAF', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nGAMaxSelProb', len: 32 } },
  { child: { type: Number, name: 'fGAMaxAF', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nMADst', len: 32 } },
  { child: { type: Number, name: 'nMASpd', len: 32 } },
  { child: { type: Number, name: 'nMAMinSelProb', len: 32 } },
  { child: { type: Number, name: 'fMAMinAF', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nMAMaxSelProb', len: 32 } },
  { child: { type: Number, name: 'fMAMaxAF', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__1', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__1', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__2', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__2', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__3', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__3', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffCode__4', len: 32 } },
  { child: { type: Number, name: 'nEffUnit__4', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nDuration', len: 32 } },
  { child: { type: Boolean, name: 'bSell', len: 32 } },
  { child: { type: Boolean, name: 'bExchange', len: 32 } },
  { child: { type: Boolean, name: 'bGround', len: 32 } },
  { child: { type: Boolean, name: 'bStoragePossible', len: 32 } },
  { child: { type: Boolean, name: 'bUseableNormalAcc', len: 32 } },
  { child: { type: Number, name: 'nUpgrade', len: 32 } },
  { child: { type: String, name: 'strTooltipIndex', len: 64 } },
  { child: { type: Number, name: 'nAttEffType', len: 32 } },
  { child: { type: Boolean, name: 'bIsTime', len: 32 } },
]);
