import Struct from '../../../classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 32, as: 'hex' } },
  { child: { type: String, name: 'strName', len: 64 } },
  { child: { type: String, name: 'strModel', len: 32, as: 'hex' } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: String, name: 'strCivil1', len: 32, as: 'hex' } },
  { child: { type: String, name: 'strCivil2', len: 32, as: 'hex' } },
  { child: { type: Number, name: 'nType', len: 8 } },
  { child: { type: Number, name: 'nMoney', len: 8 } },
  { child: { type: Number, name: 'nUnkInt16', len: 16 } },
  { child: { type: Number, name: 'nStdPrice', len: 32 } },
  { child: { type: Number, name: 'nStdPoint', len: 32 } },
  { child: { type: Number, name: 'nGoldPoint', len: 32 } },
  { child: { type: Number, name: 'nProcPoint', len: 32 } },
  { child: { type: Number, name: 'nKillPoint', len: 32 } },
  { child: { type: Number, name: 'nStoragePrice', len: 32 } },
  { child: { type: Boolean, name: 'bExchange', len: 32 } },
  { child: { type: Boolean, name: 'bSell', len: 32 } },
  { child: { type: Boolean, name: 'bGround', len: 32 } },
  { child: { type: Boolean, name: 'bStoragePossible', len: 32 } },
  { child: { type: Number, name: 'nDescription', len: 32 } },
  { child: { type: Number, name: 'bExist', len: 32 } },
  { child: { type: Number, name: 'bIsCash', len: 32 } },
  { child: { type: Number, name: 'bIsTime', len: 32 } },
  { child: { type: Number, name: 'nUpLevelLim', len: 32 } },
  { child: { type: Number, name: 'nElement', len: 8 } },
  { child: { type: Number, name: 'nUnkInt8', len: 8 }, repeat: 3 },

  { child: { type: Number, name: 'fPower', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nQuantity', len: 32 } },
  { child: { type: Number, name: 'nBulletTypeNum', len: 8 } },
  { child: { type: Number, name: 'nBulletType', len: 8 }, repeat: 4 },
  { child: { type: Number, name: 'nUnkInt8_4', len: 8 } },
  { child: { type: Number, name: 'nUnkInt8_5', len: 8 } },
  { child: { type: Number, name: 'nUnkInt8_6', len: 8 } },
  { child: { type: Number, name: 'nUnkInt32', len: 32 }, repeat: 11 },
  { child: { type: Number, name: 'nDebuff', len: 32 } },
  { child: { type: Number, name: 'nUnkInt32_12', len: 32 } },
  { child: { type: Number, name: 'nUnkInt32_13', len: 32 } },
  { child: { type: Number, name: 'nUnkInt32_14', len: 32 } },
]);
