import Struct from '../../../classes/Struct';

export default new Struct().fromSchema1([
  { child: { type: Number, name: 'nIndex', len: 32 } },
  { child: { type: String, name: 'strCode', len: 32, as: 'hex' } },
  { child: { type: String, name: 'strName', len: 64 } },
  { child: { type: String, name: 'strModel', len: 32, as: 'hex' } },
  { child: { type: Number, name: 'nIconIDX', len: 32 } },
  { child: { type: String, name: 'strCivil1', len: 32, as: 'hex' } },
  { child: { type: String, name: 'strCivil2', len: 32, as: 'hex' } },
  { child: { type: Number, name: 'nType', len: 8 } },
  { child: { type: Number, name: 'nMoney', len: 8 } },
  { child: { type: Number, name: 'nUnkInt16', len: 16 } },
  { child: { type: Number, name: 'nStdPrice', len: 32 } },
  { child: { type: Number, name: 'nStdPoint', len: 32 } },
  { child: { type: Number, name: 'nGoldPoint', len: 32 } },
  { child: { type: Number, name: 'nProcPoint', len: 32 } },
  { child: { type: Number, name: 'nKillPoint', len: 32 } },
  { child: { type: Number, name: 'nStoragePrice', len: 32 } },
  { child: { type: Number, name: 'bExchange', len: 32 } },
  { child: { type: Number, name: 'bSell', len: 32 } },
  { child: { type: Number, name: 'bGround', len: 32 } },
  { child: { type: Number, name: 'bStoragePossible', len: 32 } },
  { child: { type: Number, name: 'nDescription', len: 32 } },
  { child: { type: Number, name: 'bExist', len: 32 } },
  { child: { type: Number, name: 'bIsCash', len: 32 } },
  { child: { type: Number, name: 'bIsTime', len: 32 } },
  { child: { type: Number, name: 'nUpLevelLim', len: 32 } },

  { child: { type: Number, name: 'nEffNum', len: 32 } },
  {
    child: [
      { type: Number, name: 'nEffCode', len: 8 },
      { type: Number, name: 'nUnkInt8', len: 8 },
      { type: Number, name: 'nUnkInt16', len: 16 },
      { type: Number, name: 'fEffUnit', len: 32, as: 'float' },
      { type: Number, name: 'fEffUnitMax', len: 32, as: 'float' },
    ],
    repeat: 5,
  },
  { child: { type: Boolean, name: 'bUpgrade', len: 32 } },
  { child: { type: Number, name: 'nUpgradeType', len: 32 } },
  { child: { type: Number, name: 'nUpper', len: 8 } },
  { child: { type: Number, name: 'nLower', len: 8 } },
  { child: { type: Number, name: 'nGlove', len: 8 } },
  { child: { type: Number, name: 'nShoe', len: 8 } },
  { child: { type: Number, name: 'nHelmet', len: 8 } },
  { child: { type: Number, name: 'nWeapon', len: 8 } },
  { child: { type: Number, name: 'nShield', len: 8 } },
  { child: { type: Number, name: 'nMissile', len: 8 } },
  { child: { type: Number, name: 'nUnit', len: 8 } },
  { child: { type: Number, name: 'nCloak', len: 8 } },
  { child: { type: Number, name: 'nUpgradeEffect', len: 16 } },
  { child: { type: Number, name: 'fPlus', len: 32, as: 'float' }, repeat: 7 },
  { child: { type: Number, name: 'fJewelRate', len: 32, as: 'float' } },
  { child: { type: Number, name: 'nEffType', len: 32 } },
  { child: { type: Number, name: 'nUIPrint', len: 32 } },
  { child: { type: Number, name: 'nItemUiTip', len: 32 } },
  { child: { type: Number, name: 'nUnkInt32', len: 32 }, repeat: 3 },
]);
