import { isObject } from 'lodash';
import * as RESOURCE_TYPES from './resource_types';

export const BONE_TYPES = [
  RESOURCE_TYPES.PLAYER_BONE1,
  RESOURCE_TYPES.PLAYER_BONE2,
  RESOURCE_TYPES.PLAYER_BONE3,
  RESOURCE_TYPES.MONSTER_BONE,
  RESOURCE_TYPES.ANIMUS_BONE,
  RESOURCE_TYPES.TOWER_BONE,
  RESOURCE_TYPES.STORE_BONE,
  RESOURCE_TYPES.ITEM_BONE,
  RESOURCE_TYPES.MAU_BONE,
];

export const MESH_TYPES = [
  RESOURCE_TYPES.PLAYER_MESH1,
  RESOURCE_TYPES.PLAYER_MESH2,
  RESOURCE_TYPES.PLAYER_MESH3,
  RESOURCE_TYPES.MONSTER_MESH,
  RESOURCE_TYPES.ANIMUS_MESH,
  RESOURCE_TYPES.TOWER_MESH,
  RESOURCE_TYPES.STORE_MESH,
  RESOURCE_TYPES.ITEM_MESH,
  RESOURCE_TYPES.MAU_MESH,
];

export const ANI_TYPES = [
  RESOURCE_TYPES.PLAYER_ANI1,
  RESOURCE_TYPES.PLAYER_ANI2,
  RESOURCE_TYPES.PLAYER_ANI3,
  RESOURCE_TYPES.MONSTER_ANI,
  RESOURCE_TYPES.ANIMUS_ANI,
  RESOURCE_TYPES.TOWER_ANI,
  RESOURCE_TYPES.STORE_ANI,
  RESOURCE_TYPES.ITEM_ANI,
  RESOURCE_TYPES.MAU_ANI,
];

export const isBone = type =>
  BONE_TYPES.includes(isObject(type) ? type.type : type);

export const isMesh = type =>
  MESH_TYPES.includes(isObject(type) ? type.type : type);

export const isAni = type =>
  ANI_TYPES.includes(isObject(type) ? type.type : type);
