import gql from 'graphql-tag';

export default gql`
  fragment ItemServerNameParts on ItemServer {
    strCode
    strName
    strModel
    strCivil
    civil_bm
    civil_bf
    civil_cm
    civil_cf
    civil_a
    bExist
    nKindClt
    nFixPart
    nDefEffType
    nIconIDX
    nItemGrade
    nHelmetClass
    nLevelLim
    nUpLevelLim
    nClassGradeLim
    nExpertID1
    nExpertLim1
    nExpertID2
    nExpertLim2
    nMoney
    nStdPrice
    nStdPoint
    nGoldPoint
    nKillPoint
    nProcPoint
    nStoragePrice
    bAbr
    nDurUnit
    fEquipSpeed
    bRepair
    nRepPrice
    nEffState
    nGASpd
    nProperty
    fFireTol
    fWaterTol
    fSoilTol
    fWindTol
    fDefFc
    nDefenceDP
    nMaxDP
    fDefGap
    fDefFacing
    nEffCode__1
    fEffUnit__1
    nEffCode__2
    fEffUnit__2
    nEffCode__3
    fEffUnit__3
    nEffCode__4
    fEffUnit__4
    nDuration
    bSell
    bExchange
    bGround
    bStoragePossible
    bUseableNormalAcc
    nUpgrade
    strTooltipIndex
    bIsTime
    nActiveType
    strActiveCodeKey
    nActiveEffLvl
    fActiveProba
    strBulletType
    strEffBulletType
    nWPType
    nSubType
    strClassLim
    fAttGap
    nAttackDP
    fGADst
    nGAMinSelProb
    fGAMinAF
    nGAMaxSelProb
    fGAMaxAF
    nMADst
    nMASpd
    nMAMinSelProb
    fMAMinAF
    nMAMaxSelProb
    fMAMaxAF
    nAttEffType
    fBoosterSpeed
    bIsCash
    nEffectGroup
    fGAAF
    strEffectIndex
    bUpgrade
    nUsePCCash
    nToolClass
    strActTarget
    nPotionCheck
    nUseState
    strTargetEff
    fActDelay
    nDelayType
    nUseRange
    nPotionLim
    nMapCode__1
    nMapCode__2
    nMapCode__3
    nMapCode__4
    nMapCode__5
    strEffCode
    nEffArea
    nEffAreaVal
    nOreList
    nOreLevel
    nOreProb
    nProcessPoint
    nMinCRandom
    nMaxCRandom
    nProcessPrice
    nItemSerise
    nMixNum
    fNeedNum
    strLastItem
    nAncStdPrice
    nExStdPrice
    nMecaStdPrice
    nStartTime
    nEffContTime
    nEffType1
    nUIPrint
    nItemUITip
    nEffectDataNum
    nEffUnitMax__1
    nEffUnitMax__2
    nEffUnitMax__3
    nEffUnitMax__4
    nEffCode__5
    fEffUnit__5
    nEffUnitMax__5
    strForceCodeKey
    nFRAType
    strMapCode
    strDummyName
    nGenMob
    bQualification
    fMobAdd
    nTerminateTime
    nEndIF
    strMobID
    nMobCount
    bItemLooting
    nExp
    nDalant
    nGold
    strMissionIndex
    nAnimusClass
    nAnimusType
    strCharMeshID
    nExpertLim
    nExpTime
    nLevel
    nHeight
    nWidth
    nGADst
    nAttSklUnit
    nGAMinAF
    nGAMaxAF
    nDefSklUnit
    nDefFc
    nFireTol
    nWaterTol
    nSoilTol
    nWindTol
    nMaxHP
    strMaterialCode__1_1
    nMaterialNum__1_2
    strMaterialCode__2_1
    nMaterialNum__2_2
    strMaterialCode__3_1
    nMaterialNum__3_2
    nType
    nExpTimeSec
    bDisjointable
    nUpkeepTimeMin
    fReactionDst
    bSetTarget
    fMaxHP
    bDismantle
    nUsableType
    fMinDst
    fMaxDst
    nGACorSpd
    nMinRecoveryPro
    nMaxRecoveryPro
    strItemCode__1_1
    nItemNum__1_2
    strItemCode__2_1
    nItemNum__2_2
    strItemCode__3_1
    nItemNum__3_2
    strEffSort
    nSucPro
    strStoreNPCcode
    nNpcClass__1
    nNpcClass__2
    nNpcClass__3
    nNpcClass__4
    nNpcClass__5
    nNpcClass__6
    nNpcClass__7
    nNpcClass__8
    nNpcClass__9
    nNpcClass__10
    nStoragePart
    nCouponItemPart
    nDiscount
    nPoint
    strDefFrame
    nNeedBt
    fAttackRange
    nAttackDel
    fMoveSpdRev
    nAttMastery
    nDefMastery
    nDesrepPrice
    nBstCha
    fBstSpd
    nBackSlt
  }
`;
