import gql from 'graphql-tag';

export default gql`
  fragment NPCharacterNameParts on NPCharacter {
    strCode
    strName
    nRace
    bWarType
    fTarDecType
    fLevel
    fExt
    fAttFcStd
    fMinAFSelProb
    fMaxAFSelProb
    fAttSklUnit
    fDefSklUnit
    fWeakPart
    fStdDefFc
    fFireTol
    fWaterTol
    fSoilTol
    fWindTol
    fAttTechID1
    fAttTech1UseProb
    fAttTechID2
    fAttTech2UseProb
    fAttTechID3
    fAttTech3UseProb
    fAttTechMinAFProb
    fAttTechMinAF
    fAttTechMaxAFProb
    fAttTechMaxAF
    fPSecTechID
    fMSecTechID
    fMaxHP
    fHPRecDelay
    fHPRecUnit
    fAttSpd
    fAttMoTime1
    fAttMoTime2
    fViewExt
    fAttExt
    fMRefExt
    fCopTime
    fMovSpd
    fWarMovSpd
    fScaleRate
    bScaleChange
    fWidth
    fWaitTime
    nAsitReqRate
    nAsitAptRate
    strChildMon
    nChildMonNum
    fEmoType
    fDamHPStd
    fEmoImpStdTime
    fGoodToOrdHPPer
    fOrdToBadHPPer
    fBadToWorseHPPer
    fEspTFProb
    fTypeCompTerms
    fPSecTechChat
    fPAttTechChat
    fEmo0Chat
    fEmo0ChatProb
    fEmo1Chat
    fEmo1ChatProb
    fEmo2Chat
    fEmo2ChatProb
    fEmo3Chat
    fEmo3ChatProb
    fEmo4Chat
    fEmo4ChatProb
    fAsitReqSteEspChat
    fAsitReqSteEspChatProb
    fAsitReqSteHelpChat
    fAsitReqSteHelpChatProb
    fAsitReqSteCopChat
    fAsitReqSteCopChatProb
  }
`;
