import gql from 'graphql-tag';

export default gql`
  fragment ProjectItemClientNameParts on ProjectItemClient {
    civil_bm
    civil_bf
    civil_cm
    civil_cf
    civil_a
    strCode
    strName
    strModel
    nIconIDX
    strCivil1
    strCivil2
    nMoney
    nUnkInt16
    nStdPrice
    nStdPoint
    nGoldPoint
    nProcPoint
    nKillPoint
    nStoragePrice
    bExchange
    bSell
    bGround
    bStoragePossible
    nDescription
    bExist
    bIsCash
    bIsTime
    nUpLevelLim
    nUnkInt32
    nItemGrade
    nUnkInt32_1
    nUpgrade
    nUnkInt32_2
    nDurUnit
    nLevelLim
    nExpertID1
    nExpertID2
    nExpertLim1
    nExpertLim2
    nUnkInt8_1
    nUnkInt8_2
    nUnkInt8_3
    nGASpd
    nEffNum
    nEffCode__1
    nEffCode__2
    nEffCode__3
    nEffCode__4
    nUnkInt8_4
    nUnkInt8_5
    nUnkInt8_6
    fEffUnit__1
    fEffUnit__2
    fEffUnit__3
    fEffUnit__4
    nDefEffType
    nClassGradeLim
    nDefFc
    nFireTol
    nWaterTol
    nSoilTol
    nWindTol
    fDefGap
    fDefFacing
    nUnkInt32_3
    nAttEffType
    nWPType
    nSubType
    strClassLim
    fGADst
    nGAMinAF
    nGAMaxAF
    nMAMinAF
    nMAMaxAF
    nProperty
    nBulletType__1
    nBulletType__2
    nBulletType__3
    nBulletType__4
    nBulletTypeNum
    nActiveType
    strActiveCodeKey
    nUnkInt32_4
    fBoosterSpeed
    nElement
    nUnkInt8__1
    nUnkInt8__2
    nUnkInt8__3
    fPower
    nQuantity
    nUnkInt32__1
    nUnkInt32__2
    nUnkInt32__3
    nUnkInt32__4
    nUnkInt32__5
    nUnkInt32__6
    nUnkInt32__7
    nUnkInt32__8
    nUnkInt32__9
    nUnkInt32__10
    nUnkInt32__11
    nDebuff
    nUnkInt32_12
    nUnkInt32_13
    nUnkInt32_14
    nActDelay
    nUseState
    strActTarget1
    strActTarget2
    nDelayType
    nUseRange
    nEffCode
    nEffArea
    nEffAreaVal
    nExpTime
    nMinCRandom
    nMaxCRandom
    nUnkInt16_2
    nProcessPrice
    nOreList
    nEffCode__1_1
    nUnkInt8__1_2
    nUnkInt16__1_3
    fEffUnit__1_4
    fEffUnitMax__1_5
    nEffCode__2_1
    nUnkInt8__2_2
    nUnkInt16__2_3
    fEffUnit__2_4
    fEffUnitMax__2_5
    nEffCode__3_1
    nUnkInt8__3_2
    nUnkInt16__3_3
    fEffUnit__3_4
    fEffUnitMax__3_5
    nEffCode__4_1
    nUnkInt8__4_2
    nUnkInt16__4_3
    fEffUnit__4_4
    fEffUnitMax__4_5
    nEffCode__5_1
    nUnkInt8__5_2
    nUnkInt16__5_3
    fEffUnit__5_4
    fEffUnitMax__5_5
    bUpgrade
    nUpgradeType
    nUpper
    nLower
    nGlove
    nShoe
    nHelmet
    nWeapon
    nShield
    nMissile
    nUnit
    nCloak
    nUpgradeEffect
    fPlus__1
    fPlus__2
    fPlus__3
    fPlus__4
    fPlus__5
    fPlus__6
    fPlus__7
    fJewelRate
    nEffType
    nUIPrint
    nItemUiTip
    strForceCodekey
    nFRAType
    fUnkFloat_1
    fUnkFloat_2
    nHeight
    nWidth
    nMaxHP
    nRepPrice
    nUnitHead
    nUnitUpper
    nUnitLower
    nUnitArm
    nUnitShoulder
    nUnitBack
    nBullet1
    nBullet2
    bDestory
    bRepair
    strMapCode
    strDummyName
    bQualification
    nTerminateTime
    nEndIF
    strMobID
    nMobCount
    nExp
    nDalant
    nGold
    strCharMeshID
    nLevel
    fAttRadius
    nStartTime
    nAttMin
    nAttMax
    strUnkX32
    nSpeed
    nItemNum
    nItemType__1
    nItemType__2
    nItemType__3
    nItemType__4
    nItemType__5
    nUnkInt16_3
    strItemIndex__1
    strItemIndex__2
    strItemIndex__3
    strItemIndex__4
    strItemIndex__5
    strItemCode__1
    strItemCode__2
    strItemCode__3
    strItemCode__4
    strItemCode__5
    strItemCount__1
    strItemCount__2
    strItemCount__3
    strItemCount__4
    strItemCount__5
    nExpLim
    nExpTimeSec
    bIsUseEffect
    nUseType
    fMinDst
    fMaxDst
    fGAAF
    nGAcorSpd
    nUnkInt32_5
    strLabel1
    strLabel2
    nMin
    nMax
    fActDelay
    bAbr
    fEquipSpeed
    nSucPro
    nDuration
    nItemCount__1
    nItemCount__2
    nItemCount__3
    nUnkInt8
    strNpc
    nButton__1
    nButton__2
    nButton__3
    nButton__4
    nButton__5
    nButton__6
    nButton__7
    nButton__8
    nButton__9
    nButton__10
    nStoragePart
    nPart
    nDiscount
    nPoint
    nFixPart
    strDefFrame1
    strDefFrame2
    nAttMastery
    nDefMastery
    nUnkInt16_4
    nUnkInt32_6
    fAttRange
    nAttDelay
    nEffGroup
    nBulletType
    nBackSlot
    nBstCha
    nBstSpd
    nUnkInt16_5
    nEffID
    nNewItemType
    nNewItemIndex
    strNewItemCode
    nLink
    nPosInWindow
    nNumMaterials
    nMaterialType__1
    nMaterialType__2
    nMaterialType__3
    nMaterialType__4
    nMaterialType__5
    nMaterialIndex__1
    nMaterialIndex__2
    nMaterialIndex__3
    nMaterialIndex__4
    nMaterialIndex__5
    strMaterialCode__1
    strMaterialCode__2
    strMaterialCode__3
    strMaterialCode__4
    strMaterialCode__5
    nMaterialCount__1
    nMaterialCount__2
    nMaterialCount__3
    nMaterialCount__4
    nMaterialCount__5
    nCombineIndex
    nCostOperation
    nTradeMoney
    nUnkInt16_1
    nTradeValue
    strUnk100
    nUnkInt32__12
    nUnkInt32__13
    nUnkInt32__14
    nUnkInt32__15
    nUnkInt32__16
    nUnkInt32__17
    nUnkInt32__18
    nUnkInt32__19
    nUnkInt32__20
    nUnkInt32__21
    nUnkInt32__22
    nUnkInt32__23
    nUnkInt32__24
    nUnkInt32__25
    nUnkInt32__26
    nUnkInt32__27
    nUnkInt32__28
    nUnkInt32__29
    nUnkInt32__30
    nUnkInt32__31
    nUnkInt32__32
    nUnkInt32__33
    nUnkInt32__34
    nUnkInt32__35
    nUnkInt32__36
    nUnkInt32__37
    nUnkInt32__38
    nUnkInt32__39
    nUnkInt32__40
    nUnkInt32__41
    nUnkInt32__42
    nUnkInt32__43
    nUnkInt32__44
    nUnkInt32__45
    nUnkInt32__46
  }
`;
